### ISSUE TITLE
Doesn't work on Chrome OS X

### ISSUE THREAD

**Issue by icerfish** [sgb-io/game-jam#1]
On clicking "Start" after selecting a sample or uploading a face throws the following error on line 68 of index.

```
Uncaught TypeError: Failed to execute 'animate' on 'Element': Valid arities are: [1], but 0 arguments provided.
```

**Comment by sgb-io** [comment]
Hey @icerfish, this project is no longer maintained. Indeed it no longer works on Chrome — something must have been deprecated or changed in stable.

You could try updating all the dependencies and going from there.

**Comment by icerfish** [comment]
Hi @samuelgbrown, I've since fixed the bug and submitted a pull request!

**Comment by sgb-io** [comment]
you're awesome! @icerfish - hope its useful, or at least fun! :muscle:

**Comment by icerfish** [comment]
I work at unit9. I noticed it was broken and nothing else to do so I thought I would fix it :)

**Comment by sgb-io** [comment]
:+1:
